name: regrowth_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.3.3+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.8
  dio: ^5.7.0
  intl: ^0.20.0
  provider: ^6.1.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterExtraLight.ttf
          weight: 400
        - asset: assets/fonts/InterRegular.ttf
          weight: 600

    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600

    - family: Lexend
      fonts:
        - asset: assets/fonts/LexendMedium.ttf
          weight: 400
        - asset: assets/fonts/LexendRegular.ttf
          weight: 600
        - asset: assets/fonts/LexendSemiBold.ttf
          weight: 500
